# Usar uma imagem base do Python
FROM python:3.9-slim

# Definir o diretório de trabalho no container
WORKDIR /app

# Copiar o script Python para o diretório de trabalho
COPY carguru.py .

# Executar o script Python quando o container for iniciado
CMD ["python", "carguru.py"]
